// <auto-generated />
using System;
using BookLendingApp.DALLibrary.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookLendingApp.DALLibrary.Migrations
{
    [DbContext(typeof(BookLendingAppContext))]
    [Migration("20260517171022_Ispaid")]
    partial class Ispaid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookLendingApp.ModelLibrary.Models.Book", b =>
                {
                    b.Property<Guid>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("integer");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BookLendingApp.ModelLibrary.Models.BookCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BookLendingApp.ModelLibrary.Models.BookCopy", b =>
                {
                    b.Property<Guid>("BookCopyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DamagePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("ShelfLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BookCopyId");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("BookId");

                    b.ToTable("BookCopies");
                });

            modelBuilder.Entity("BookLendingApp.ModelLibrary.Models.BorrowRecord", b =>
                {
                    b.Property<Guid>("BorrowRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookCopyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BorrowStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DamagePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("RenewalCount")
                        .HasColumnType("integer");

                    b.Property<int>("RenewalDays")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BorrowRecordId");

                    b.HasIndex("BookCopyId");

                    b.HasIndex("MemberId");

                    b.ToTable("BorrowRecords");
                });

            modelBuilder.Entity("BookLendingApp.ModelLibrary.Models.FineRule", b =>
                {
                    b.Property<Guid>("FineAmountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("FineCalculationType")
                        .HasColumnType("integer");

                    b.Property<int>("FineType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FineAmountId");

                    b.ToTable("FineRules");
                });

            modelBuilder.Entity("BookLendingApp.ModelLibrary.Models.Member", b =>
                {
                    b.Property<Guid>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MemberId");

                    b.HasIndex("EmailId")
                        .IsUnique();

                    b.HasIndex("MembershipId");

                    b.HasIndex("MobileNumber")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("BookLendingApp.ModelLibrary.Models.MemberShip", b =>
                {
                    b.Property<Guid>("MemberShipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRenewalAllowed")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxBooksAllowed")
                        .HasColumnType("integer");

                    b.Property<int>("MaxBorrowDurationDays")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRenewalDurationDays")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRenewalTimes")
                        .HasColumnType("integer");

                    b.Property<decimal>("MembershipFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MemberShipId");

                    b.ToTable("MemberShips");
                });

            modelBuilder.Entity("BookLendingApp.ModelLibrary.Models.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("BorrowRecordId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentDiscriminator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("PaymentDiscriminator");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer");

                    b.HasKey("PaymentId");

                    b.HasIndex("BorrowRecordId");

                    b.HasIndex("MemberId");

                    b.ToTable("Payments");

                    b.HasDiscriminator<string>("PaymentDiscriminator").HasValue("Payment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BookLendingApp.ModelLibrary.Models.BookDamageFeePayment", b =>
                {
                    b.HasBaseType("BookLendingApp.ModelLibrary.Models.Payment");

                    b.HasDiscriminator().HasValue("BookDamageFeePayment");
                });

            modelBuilder.Entity("BookLendingApp.ModelLibrary.Models.LateFeePayment", b =>
                {
                    b.HasBaseType("BookLendingApp.ModelLibrary.Models.Payment");

                    b.HasDiscriminator().HasValue("LateFeePayment");
                });

            modelBuilder.Entity("BookLendingApp.ModelLibrary.Models.LostBookFeePayment", b =>
                {
                    b.HasBaseType("BookLendingApp.ModelLibrary.Models.Payment");

                    b.HasDiscriminator().HasValue("LostBookFeePayment");
                });

            modelBuilder.Entity("BookLendingApp.ModelLibrary.Models.MembershipPayment", b =>
                {
                    b.HasBaseType("BookLendingApp.ModelLibrary.Models.Payment");

                    b.HasDiscriminator().HasValue("MembershipPayment");
                });

            modelBuilder.Entity("BookLendingApp.ModelLibrary.Models.OtherPayment", b =>
                {
                    b.HasBaseType("BookLendingApp.ModelLibrary.Models.Payment");

                    b.HasDiscriminator().HasValue("OtherPayment");
                });

            modelBuilder.Entity("BookLendingApp.ModelLibrary.Models.RenewalFeePayment", b =>
                {
                    b.HasBaseType("BookLendingApp.ModelLibrary.Models.Payment");

                    b.HasDiscriminator().HasValue("RenewalFeePayment");
                });

            modelBuilder.Entity("BookLendingApp.ModelLibrary.Models.Book", b =>
                {
                    b.HasOne("BookLendingApp.ModelLibrary.Models.BookCategory", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BookLendingApp.ModelLibrary.Models.BookCopy", b =>
                {
                    b.HasOne("BookLendingApp.ModelLibrary.Models.Book", "Book")
                        .WithMany("BookCopies")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BookLendingApp.ModelLibrary.Models.BorrowRecord", b =>
                {
                    b.HasOne("BookLendingApp.ModelLibrary.Models.BookCopy", "BookCopy")
                        .WithMany("BorrowRecords")
                        .HasForeignKey("BookCopyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookLendingApp.ModelLibrary.Models.Member", "Member")
                        .WithMany("BorrowRecords")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookCopy");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("BookLendingApp.ModelLibrary.Models.Member", b =>
                {
                    b.HasOne("BookLendingApp.ModelLibrary.Models.MemberShip", "Membership")
                        .WithMany("Members")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("BookLendingApp.ModelLibrary.Models.Payment", b =>
                {
                    b.HasOne("BookLendingApp.ModelLibrary.Models.BorrowRecord", "BorrowRecord")
                        .WithMany("Payments")
                        .HasForeignKey("BorrowRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BookLendingApp.ModelLibrary.Models.Member", "Member")
                        .WithMany("Payments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BorrowRecord");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("BookLendingApp.ModelLibrary.Models.Book", b =>
                {
                    b.Navigation("BookCopies");
                });

            modelBuilder.Entity("BookLendingApp.ModelLibrary.Models.BookCategory", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookLendingApp.ModelLibrary.Models.BookCopy", b =>
                {
                    b.Navigation("BorrowRecords");
                });

            modelBuilder.Entity("BookLendingApp.ModelLibrary.Models.BorrowRecord", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BookLendingApp.ModelLibrary.Models.Member", b =>
                {
                    b.Navigation("BorrowRecords");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BookLendingApp.ModelLibrary.Models.MemberShip", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
